Option to suppress petget failure warning on installed pkgs

diff --git a/usr/local/petget/petget b/usr/local/petget/petget
--- a/usr/local/petget/petget
+++ b/usr/local/petget/petget
@@ -255,12 +255,17 @@ rm -f $PKGPATH/${PKGNAME}.tar.gz 2>/dev/null
 
 #announce result...
 if [ $RETVAL -ne 0 -o ! -s /tmp/petget-installed-pkgs-log ];then
- if [ "$DISPLAY" ]; then
-  /usr/lib/gtkdialog/box_ok "$(gettext 'Puppy Package Manager')" error "<b>${FULLPKGNAME} $(gettext 'failed to install.')</b>"
-  exit
+ if [ "$(grep ^${PKGNAME} /root/.packages/user-installed-packages)" != "" \
+  -a  "$(cat /var/local/petget/nw_category)" = "true" ];then
+   exit 1
  else
-  dialog --msgbox "$FULLPKGNAME $(gettext ' failed to install') " 0 0
-  exit
+  if [ "$DISPLAY" ]; then
+   /usr/lib/gtkdialog/box_ok "$(gettext 'Puppy Package Manager')" error "<b>${FULLPKGNAME} $(gettext 'failed to install.')</b>"
+   exit
+  else
+   dialog --msgbox "$FULLPKGNAME $(gettext ' failed to install') " 0 0
+   exit
+  fi
  fi
 fi
 
